//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCSWEntities : DbContext
    {
        public PCSWEntities()
            : base("name=PCSWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DistrictData> DistrictDatas { get; set; }
        public virtual DbSet<ProvincialBoard> ProvincialBoards { get; set; }
        public virtual DbSet<ProvincialCommittee> ProvincialCommittees { get; set; }
        public virtual DbSet<ProvincialData> ProvincialDatas { get; set; }
        public virtual DbSet<ProvincialTaskForce> ProvincialTaskForces { get; set; }
    }
}
