//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvincialData
    {
        public int P_Id { get; set; }
        public string P_Type { get; set; }
        public string Departments { get; set; }
        public int NumEmployeeMale { get; set; }
        public int NumEmployeeFemale { get; set; }
        public int NumEmployeeMaleFrom2012 { get; set; }
        public int NumEmployeeFemaleFrom2012 { get; set; }
        public int NumGazettedMale { get; set; }
        public int NumGazettedFemale { get; set; }
        public int NumGazettedMaleFrom2012 { get; set; }
        public int NumGazettedFemaleFrom2012 { get; set; }
        public int NumNonGazettedMale { get; set; }
        public int NumNonGazettedFemale { get; set; }
        public int NumNonGazettedMaleFrom2012 { get; set; }
        public int NumNonGazettedFemaleFrom2012 { get; set; }
        public int NumContractMale { get; set; }
        public int NumContractFemale { get; set; }
        public int NumContractMaleFrom2012 { get; set; }
        public int NumContractFemaleFrom2012 { get; set; }
        public int NumWomenWashrooms { get; set; }
        public int NumWomenPrayerRooms { get; set; }
        public int NumAgeRelaxation3 { get; set; }
        public int NumMaternityLeave { get; set; }
        public int NumPaternityLeave { get; set; }
        public int NumSRCForRegular { get; set; }
        public int NumSRCForRegularWithOneWomen { get; set; }
        public string GMCEstablishment { get; set; }
        public string COCImplementation { get; set; }
        public string EstablishmentWHC { get; set; }
        public int NumComplaints { get; set; }
        public int NumActionsTaken { get; set; }
        public int NumBoardBCT { get; set; }
        public int NumCommitteeBCT { get; set; }
        public int NumTaskForceBCT { get; set; }
    }
}
